package frames;

import frames.forms.AppsProfileForm;
import helper.DBTransactions;
import helper.PopupMessage;
import config.SystemPath;
import helper.TableRender;
import helper.objects.AppsProfile;
import java.awt.Point;
import java.util.ArrayList;

/**
 *
 * @author staff
 */
public class AppsProfileManagerFrame extends WindowsSkeleton {

    /**
     * Creates new form AppProfileManagerFrame
     */
    DBTransactions db = new DBTransactions(SystemPath.DB_FILE);
    TableRender tbrend = new TableRender();

    DashboardFrame parent;
    ArrayList<AppsProfile> dataTemp = new ArrayList<>();
    ArrayList<AppsProfile> dataFound = new ArrayList<>();

    public AppsProfileManagerFrame() {
        prepareUI();
    }

    public AppsProfileManagerFrame(DashboardFrame parentNa) {
        parent = parentNa;
        prepareUI();
    }

    private void prepareUI() {
        super.windowsTheme();
        initComponents();
        refresh();
        this.toFront();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAppProfile = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        textfield_search = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelAppDescription = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        tableAppProfile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "[#]", "id", "App Name", "Type", "Version"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAppProfile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tableAppProfileMouseMoved(evt);
            }
        });
        tableAppProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tableAppProfileMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(tableAppProfile);
        if (tableAppProfile.getColumnModel().getColumnCount() > 0) {
            tableAppProfile.getColumnModel().getColumn(0).setMinWidth(30);
            tableAppProfile.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableAppProfile.getColumnModel().getColumn(0).setMaxWidth(30);
            tableAppProfile.getColumnModel().getColumn(1).setMinWidth(0);
            tableAppProfile.getColumnModel().getColumn(1).setPreferredWidth(0);
            tableAppProfile.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        jPanel2.setPreferredSize(new java.awt.Dimension(544, 40));
        jPanel2.setLayout(new java.awt.BorderLayout());

        textfield_search.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        textfield_search.setText("search...");
        textfield_search.setPreferredSize(new java.awt.Dimension(160, 10));
        textfield_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfield_searchMouseClicked(evt);
            }
        });
        textfield_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfield_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfield_searchKeyTyped(evt);
            }
        });
        jPanel2.add(textfield_search, java.awt.BorderLayout.WEST);

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        jPanel5.add(buttonAdd);

        buttonEdit.setText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });
        jPanel5.add(buttonEdit);

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(buttonDelete);

        jPanel2.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        labelAppDescription.setText("-hover your app data above to see the result here-");
        jPanel3.add(labelAppDescription);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);
        jPanel4.setPreferredSize(new java.awt.Dimension(338, 100));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apps Profile Manager");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed

        AppsProfileForm frame = new AppsProfileForm(this);
        frame.setVisible(true);

        this.setEnabled(false);

    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed

        int nomer = tbrend.getCheckedData(tableAppProfile, 1);
        if (nomer != TableRender.DATA_NOT_AVAILABLE) {
            db.delete_specific_AppProfile(nomer);
            refresh();
        } else {
            PopupMessage.showError("no data selected!");
        }


    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed

        int nomer = tbrend.getCheckedData(tableAppProfile, 1);
        if (nomer != TableRender.DATA_NOT_AVAILABLE) {
            AppsProfile data = db.select_specific_AppProfile(nomer);
            AppsProfileForm frame = new AppsProfileForm(this);
            frame.setData(data);
            frame.setVisible(true);
            refresh();
        } else {
            PopupMessage.showError("no data selected!");
        }

    }//GEN-LAST:event_buttonEditActionPerformed

    private void tableAppProfileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAppProfileMouseMoved

        Point point = evt.getPoint();
        int row = tableAppProfile.rowAtPoint(point);

        System.out.println("Baris ke " + row);

        if (row != TableRender.DATA_NOT_AVAILABLE) {
            int id = (Integer) tableAppProfile.getValueAt(row, 1);
            AppsProfile data = db.select_specific_AppProfile(id);

            System.out.println("Datana " + data.getDescription());

            if (data.getDescription() != null) {
                labelAppDescription.setText(data.getDescription());
            } else {
                labelAppDescription.setText("-");
            }

        }

    }//GEN-LAST:event_tableAppProfileMouseMoved

    private void tableAppProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAppProfileMouseExited
        labelAppDescription.setText("-hover your app data above to see the result here-");
    }//GEN-LAST:event_tableAppProfileMouseExited

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        if (parent != null) {
            parent.setEnabled(true);
            parent.toFront();
        }
    }//GEN-LAST:event_formWindowClosed

    private void textfield_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfield_searchKeyTyped
       

    }//GEN-LAST:event_textfield_searchKeyTyped

    private void textfield_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfield_searchMouseClicked
        
        String isian = textfield_search.getText();
        
        if(isian.equalsIgnoreCase("search...")){
            textfield_search.setText("");
        }else if(isian.length()==0){
            textfield_search.setText("search...");
        }
        
    }//GEN-LAST:event_textfield_searchMouseClicked

    private void textfield_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfield_searchKeyReleased

         String dicari = textfield_search.getText();

        if (dicari.length() > 0) {

           // System.out.println("cari " + dicari);
            
            dataFound = new ArrayList<>();

            // do the search
            for (AppsProfile dat : dataTemp) {
                if (isContains(dat.getDescription(), dicari) ||
                        isContains(dat.getName(), dicari) ||
                        isContains(dat.getPlatform_Type(), dicari) ||
                        isContains(dat.getVersion(), dicari)) {
                    dataFound.add(dat);
                }
            }


            refreshFound();

        } else {
            refresh();
        }

        
    }//GEN-LAST:event_textfield_searchKeyReleased

    private boolean isContains(String n, String x){
        return (n.toLowerCase().contains(x));
    }
    
    public void refresh() {
        dataTemp = db.select_all_AppProfile();
        tbrend.render_AppProfile(tableAppProfile, dataTemp);
    }

    public void refreshFound() {
        tbrend.render_AppProfile(tableAppProfile, dataFound);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppsProfileManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppsProfileManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppsProfileManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppsProfileManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppsProfileManagerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAppDescription;
    private javax.swing.JTable tableAppProfile;
    private javax.swing.JTextField textfield_search;
    // End of variables declaration//GEN-END:variables
}
