/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

/**
 *
 * @author asus
 */
import config.SystemApp;
import config.SystemPath;
import frames.forms.DownloadLinkForm;
import frames.forms.UserSettingsForm;
import frames.forms.WebToAPKForm;
import helper.CustomListCellRenderer;
import helper.DBTransactions;
import helper.PopupMessage;
import helper.URLManager;
import helper.UpdateChecker;
import helper.objects.ListItem;
import helper.objects.UserSettings;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URI;
import javax.swing.*;

public class DashboardFrame extends WindowsSkeleton {

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        prepareUI();
    }

    LoginFrame parent;

    public DashboardFrame(LoginFrame f) {
        parent = f;

        prepareUI();
    }

    CardLayout cpanel = null;
    DBTransactions db = new DBTransactions(SystemPath.DB_FILE);

    public void updateCheckWork() {

        UserSettings user = db.select_specific_UserSettings(1);

        UpdateChecker work = new UpdateChecker();

        work.checkWhen(work.asOptions(user.getCheck_updates()));

        if (!work.isTurned_off() && work.isUpdates_ready()) {

            int res = PopupMessage.showConfirmation("New update is ready. Do you want to download now?");
            if (res == JOptionPane.YES_OPTION) {

                work.downloadNow();
                
            } 
        }

    }

    private void prepareUI() {
        super.windowsTheme();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle(SystemApp.APP_NAME);

        listModel.addElement(new ListItem("Title 1", "Description 1", "2023-12-22"));
        listModel.addElement(new ListItem("Title 2", "Description 2", "2023-11-11"));
        listModel.addElement(new ListItem("Title 3", "Description 3", "2023-10-09"));

        // open card to notification page
        listNotification.setCellRenderer((ListCellRenderer) new CustomListCellRenderer());

        cpanel = (CardLayout) panelCenter.getLayout();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        labelNotification = new javax.swing.JLabel();
        labelUserSettings = new javax.swing.JLabel();
        labelAboutInfo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        panelCenter = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        button_apps_profile_manager = new javax.swing.JButton();
        button_license_manager = new javax.swing.JButton();
        button_download_link_render = new javax.swing.JButton();
        button_landing_page = new javax.swing.JButton();
        button_book_app_maker = new javax.swing.JButton();
        button_questions = new javax.swing.JButton();
        panelNotifications = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        labelHomeFromBookAppMaker = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNotification = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FGI Business Tools (ver.1.0a)");
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FGI Business Tools");
        jLabel1.setPreferredSize(new java.awt.Dimension(343, 100));
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel10.setPreferredSize(new java.awt.Dimension(1253, 30));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        labelNotification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/blue-mail-open-icon32.png"))); // NOI18N
        labelNotification.setText("<html><u>Notifications</u></html>");
        labelNotification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelNotification.setIconTextGap(0);
        labelNotification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelNotificationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelNotificationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelNotificationMouseExited(evt);
            }
        });
        jPanel10.add(labelNotification);

        labelUserSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/blue-user-icon32.png"))); // NOI18N
        labelUserSettings.setIcon(blue_user);
        labelUserSettings.setText("<html><u>User Settings</u></html>");
        labelUserSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelUserSettings.setIconTextGap(0);
        labelUserSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUserSettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelUserSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelUserSettingsMouseExited(evt);
            }
        });
        jPanel10.add(labelUserSettings);

        labelAboutInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/blue-picture-icon32.png"))); // NOI18N
        labelAboutInfo.setIcon(blue_about);
        labelAboutInfo.setText("<html><u>About</u></html>");
        labelAboutInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAboutInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAboutInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelAboutInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelAboutInfoMouseExited(evt);
            }
        });
        jPanel10.add(labelAboutInfo);

        jPanel1.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.EAST);

        jPanel5.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.WEST);

        panelCenter.setLayout(new java.awt.CardLayout());

        panelMenu.setPreferredSize(new java.awt.Dimension(100, 100));
        panelMenu.setLayout(new java.awt.GridLayout(2, 3, 25, 25));

        button_apps_profile_manager.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        button_apps_profile_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/blue-tag-icon.png"))); // NOI18N
        button_apps_profile_manager.setText("Apps Profile Manager");
        button_apps_profile_manager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_apps_profile_manager.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_apps_profile_manager.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_apps_profile_manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_apps_profile_managerActionPerformed(evt);
            }
        });
        panelMenu.add(button_apps_profile_manager);

        button_license_manager.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        button_license_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/blue-laptop-icon.png"))); // NOI18N
        button_license_manager.setText("License Manager");
        button_license_manager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_license_manager.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_license_manager.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_license_manager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_license_managerMouseClicked(evt);
            }
        });
        panelMenu.add(button_license_manager);

        button_download_link_render.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        button_download_link_render.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/blue-document-download-icon.png"))); // NOI18N
        button_download_link_render.setText("Download Link Renderer");
        button_download_link_render.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_download_link_render.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_download_link_render.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_download_link_render.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_download_link_renderActionPerformed(evt);
            }
        });
        panelMenu.add(button_download_link_render);

        button_landing_page.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        button_landing_page.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/blue-star-icon.png"))); // NOI18N
        button_landing_page.setText("Landing Pages");
        button_landing_page.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_landing_page.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_landing_page.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_landing_page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_landing_pageActionPerformed(evt);
            }
        });
        panelMenu.add(button_landing_page);

        button_book_app_maker.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        button_book_app_maker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/blue-web-to-android.png"))); // NOI18N
        button_book_app_maker.setText("Web to Android APK");
        button_book_app_maker.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_book_app_maker.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_book_app_maker.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_book_app_maker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_book_app_makerActionPerformed(evt);
            }
        });
        panelMenu.add(button_book_app_maker);

        button_questions.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        button_questions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/blue-mail-send-icon.png"))); // NOI18N
        button_questions.setText("Questions?");
        button_questions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_questions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_questions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_questions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_questionsActionPerformed(evt);
            }
        });
        panelMenu.add(button_questions);

        panelCenter.add(panelMenu, "menu");

        panelNotifications.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        labelHomeFromBookAppMaker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/red-home-icon.png"))); // NOI18N
        labelHomeFromBookAppMaker.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelHomeFromBookAppMaker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHomeFromBookAppMakerMouseClicked(evt);
            }
        });
        jPanel8.add(labelHomeFromBookAppMaker);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("> Notifications");
        jPanel8.add(jLabel10);

        panelNotifications.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel9.setLayout(new java.awt.BorderLayout());

        listNotification.setModel((DefaultListModel)listModel);
        listNotification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(listNotification);

        jPanel9.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1053, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        panelNotifications.add(jPanel9, java.awt.BorderLayout.CENTER);

        panelCenter.add(panelNotifications, "notifications");

        jPanel2.add(panelCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(1385, 60));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1253, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_license_managerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_license_managerMouseClicked

        showPopupMenu(evt.getComponent(), evt.getX(), evt.getY());

    }//GEN-LAST:event_button_license_managerMouseClicked

    private void button_apps_profile_managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_apps_profile_managerActionPerformed

        AppsProfileManagerFrame frame = new AppsProfileManagerFrame(this);
        frame.setVisible(true);

        this.setEnabled(false);

    }//GEN-LAST:event_button_apps_profile_managerActionPerformed

    private void button_download_link_renderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_download_link_renderActionPerformed

        DownloadLinkForm frame = new DownloadLinkForm(this);
        frame.setVisible(true);

        this.setEnabled(false);

    }//GEN-LAST:event_button_download_link_renderActionPerformed

    private void button_questionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_questionsActionPerformed

        try {
            PopupMessage.showInfo("Every questions will be forwarded by your Whatsapp.");

            Desktop.getDesktop().browse(new URI(URLManager.getWhatsappWebURL()));

        } catch (Exception ex) {

        }

    }//GEN-LAST:event_button_questionsActionPerformed

    private void button_landing_pageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_landing_pageActionPerformed

        LandingPageFrame frame = new LandingPageFrame();
        frame.setVisible(true);

    }//GEN-LAST:event_button_landing_pageActionPerformed

    private void button_book_app_makerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_book_app_makerActionPerformed

        WebToAPKManagerFrame window = new WebToAPKManagerFrame(this);
        window.setVisible(true);

        this.setEnabled(false);

    }//GEN-LAST:event_button_book_app_makerActionPerformed

    ImageIcon yellow_mailClosed = new javax.swing.ImageIcon(getClass().getResource("/frames/images/yellow-mail-icon32.png"));
    ImageIcon yellow_about = new javax.swing.ImageIcon(getClass().getResource("/frames/images/yellow-picture-icon32.png"));
    ImageIcon yellow_mailOpened = new javax.swing.ImageIcon(getClass().getResource("/frames/images/yellow-mail-open-icon32.png"));
    ImageIcon yellow_user = new javax.swing.ImageIcon(getClass().getResource("/frames/images/yellow-user-icon32.png"));
    ImageIcon blue_mailClosed = new javax.swing.ImageIcon(getClass().getResource("/frames/images/blue-mail-icon32.png"));
    ImageIcon blue_mailOpened = new javax.swing.ImageIcon(getClass().getResource("/frames/images/blue-mail-open-icon32.png"));
    ImageIcon blue_user = new javax.swing.ImageIcon(getClass().getResource("/frames/images/blue-user-icon32.png"));
    ImageIcon blue_about = new javax.swing.ImageIcon(getClass().getResource("/frames/images/blue-picture-icon32.png"));


    private void labelNotificationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNotificationMouseEntered

        // lets check whether there's available notification (0) mark or not?
        if (labelNotification.getText().contains("(")) {
            labelNotification.setIcon(yellow_mailClosed);
        } else {
            labelNotification.setIcon(yellow_mailOpened);
        }

    }//GEN-LAST:event_labelNotificationMouseEntered

    private void labelNotificationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNotificationMouseExited
        if (labelNotification.getText().contains("(")) {
            labelNotification.setIcon(blue_mailClosed);
        } else {
            labelNotification.setIcon(blue_mailOpened);
        }
    }//GEN-LAST:event_labelNotificationMouseExited

    private void labelUserSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUserSettingsMouseEntered
        if (labelUserSettings.getIcon() == blue_user) {
            labelUserSettings.setIcon(yellow_user);
        } else {
            labelUserSettings.setIcon(blue_user);
        }
    }//GEN-LAST:event_labelUserSettingsMouseEntered

    private void labelUserSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUserSettingsMouseExited
        if (labelUserSettings.getIcon() == yellow_user) {
            labelUserSettings.setIcon(blue_user);
        } else {
            labelUserSettings.setIcon(yellow_user);
        }
    }//GEN-LAST:event_labelUserSettingsMouseExited

    private void labelUserSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUserSettingsMouseClicked
        UserSettingsForm form = new UserSettingsForm(this);
        form.setVisible(true);

        this.setEnabled(false);
    }//GEN-LAST:event_labelUserSettingsMouseClicked

    private void labelAboutInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAboutInfoMouseClicked
        PopupMessage.showInfo(SystemApp.APP_NAME + " " + SystemApp.VERSION);
    }//GEN-LAST:event_labelAboutInfoMouseClicked

    private void labelAboutInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAboutInfoMouseEntered
        if (labelAboutInfo.getIcon() == blue_about) {
            labelAboutInfo.setIcon(yellow_about);
        } else {
            labelAboutInfo.setIcon(blue_about);
        }
    }//GEN-LAST:event_labelAboutInfoMouseEntered

    private void labelAboutInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAboutInfoMouseExited
        if (labelAboutInfo.getIcon() == yellow_about) {
            labelAboutInfo.setIcon(blue_about);
        } else {
            labelAboutInfo.setIcon(yellow_about);
        }
    }//GEN-LAST:event_labelAboutInfoMouseExited

    DefaultListModel<ListItem> listModel = new DefaultListModel<>();


    private void labelNotificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNotificationMouseClicked

        cpanel.show(panelCenter, "notifications");


    }//GEN-LAST:event_labelNotificationMouseClicked

    private void labelHomeFromBookAppMakerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHomeFromBookAppMakerMouseClicked

        cpanel.show(panelCenter, "menu");

    }//GEN-LAST:event_labelHomeFromBookAppMakerMouseClicked

    private static void showPopupMenu(Component invoker, int x, int y) {
        JPopupMenu popupMenu = new JPopupMenu();

        JMenuItem desktopAppMenu = new JMenuItem("Desktop or Web App");
        desktopAppMenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FlashDiskMakerFrame frame = new FlashDiskMakerFrame();
                frame.setVisible(true);

            }
        });
        popupMenu.add(desktopAppMenu);

        JMenuItem mobileAppMenu = new JMenuItem("Mobile App");
        mobileAppMenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        popupMenu.add(mobileAppMenu);

        // Show the popup menu
        popupMenu.show(invoker, x, y);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_apps_profile_manager;
    private javax.swing.JButton button_book_app_maker;
    private javax.swing.JButton button_download_link_render;
    private javax.swing.JButton button_landing_page;
    private javax.swing.JButton button_license_manager;
    private javax.swing.JButton button_questions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAboutInfo;
    private javax.swing.JLabel labelHomeFromBookAppMaker;
    private javax.swing.JLabel labelNotification;
    private javax.swing.JLabel labelUserSettings;
    private javax.swing.JList<String> listNotification;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelNotifications;
    // End of variables declaration//GEN-END:variables
}
