package frames;

/**
 *
 * @author staff
 */
import helper.DBTransactions;
import helper.DataTransporter;
import config.SystemPath;
import helper.USBFormatter;
import helper.USBInfo;
import helper.objects.AppsProfile;
import helper.objects.SingleData;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;

import javax.swing.filechooser.FileSystemView;

public class FlashDiskMakerFrame extends WindowsSkeleton {

    /**
     * Creates new form FlashDiskMaker
     */
    DBTransactions db = new DBTransactions(SystemPath.DB_FILE);

    private void prepareUI() {
        super.windowsTheme();
        initComponents();
        refresh();
        this.toFront();
    }

    private void refresh() {
        comboboxUSBDriveActive.removeAllItems();
        comboboxAppProfileName.removeAllItems();
        panelProgress.setVisible(false);

        ArrayList<AppsProfile> data = db.select_all_AppProfile();
        for (AppsProfile ap : data) {
            comboboxAppProfileName.addItem(ap.getName() + " ver : " + ap.getVersion() + " platform type : " + ap.getPlatform_Type());
        }
    }

    public FlashDiskMakerFrame() {
        prepareUI();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonDetectUSBDrives = new javax.swing.JButton();
        comboboxUSBDriveActive = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        labelUSBIcon = new javax.swing.JLabel();
        buttonFDActivator = new javax.swing.JButton();
        textfieldSerialNumberUSBDevice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panelProgress = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        labelProgress = new javax.swing.JLabel();
        comboboxAppProfileName = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonDetectUSBDrives.setText("Detect USB");
        buttonDetectUSBDrives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDetectUSBDrivesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDetectUSBDrives, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 119, -1, -1));

        comboboxUSBDriveActive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxUSBDriveActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxUSBDriveActiveActionPerformed(evt);
            }
        });
        getContentPane().add(comboboxUSBDriveActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 160, 146, -1));

        jLabel1.setText("USB Drive :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 163, -1, -1));

        labelUSBIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUSBIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/usb-drive-off-32.png"))); // NOI18N
        getContentPane().add(labelUSBIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 84, -1, 72));

        buttonFDActivator.setText("Create as FD Activator");
        buttonFDActivator.setEnabled(false);
        buttonFDActivator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFDActivatorActionPerformed(evt);
            }
        });
        getContentPane().add(buttonFDActivator, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 236, -1, -1));

        textfieldSerialNumberUSBDevice.setEditable(false);
        getContentPane().add(textfieldSerialNumberUSBDevice, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 198, 267, -1));

        jLabel2.setText("Serial Number : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 201, -1, -1));

        jLabel3.setText("Progress : ");

        labelProgress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelProgress.setText("Done!");

        javax.swing.GroupLayout panelProgressLayout = new javax.swing.GroupLayout(panelProgress);
        panelProgress.setLayout(panelProgressLayout);
        panelProgressLayout.setHorizontalGroup(
            panelProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProgressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelProgress)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        panelProgressLayout.setVerticalGroup(
            panelProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProgressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelProgress)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(panelProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 277, -1, -1));

        comboboxAppProfileName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboboxAppProfileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 160, -1, -1));

        jLabel4.setText("Apps Profile : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 163, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Flashdisk Maker");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 619, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDetectUSBDrivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDetectUSBDrivesActionPerformed

        FileSystemView fsv = FileSystemView.getFileSystemView();

        File[] drives = File.listRoots();
        if (drives != null && drives.length > 0) {
            for (File aDrive : drives) {
                System.out.println("Drive Letter: " + aDrive);
                System.out.println("\tType: " + fsv.getSystemTypeDescription(aDrive));
                System.out.println("\tTotal space: " + aDrive.getTotalSpace());
                System.out.println("\tFree space: " + aDrive.getFreeSpace());
                System.out.println();

                if (fsv.getSystemTypeDescription(aDrive) != null) {
                    if (fsv.getSystemTypeDescription(aDrive).equalsIgnoreCase("usb drive")) {
                        comboboxUSBDriveActive.addItem(aDrive.getAbsolutePath());
                        foundUSB = true;

                        activateIcon();
                    }
                }

            }
        }

    }//GEN-LAST:event_buttonDetectUSBDrivesActionPerformed

    private void comboboxUSBDriveActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxUSBDriveActiveActionPerformed
        if (comboboxUSBDriveActive.getSelectedItem() != null) {
            String sn = USBInfo.getDeviceSerialNumber(comboboxUSBDriveActive.getSelectedItem().toString());
            textfieldSerialNumberUSBDevice.setText(sn);

            buttonFDActivator.setEnabled(true);
        }
    }//GEN-LAST:event_comboboxUSBDriveActiveActionPerformed

    private void buttonFDActivatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFDActivatorActionPerformed
        String driveNa = comboboxUSBDriveActive.getSelectedItem().toString();

        buttonFDActivator.setEnabled(false);
        panelProgress.setVisible(true);
        labelProgress.setVisible(false);

        Thread timerThread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    USBFormatter.formatNow(driveNa);

                    int n = 0;
                    while (n != 9) {
                        System.out.println("Loading...");
                        // Sleep for 9 seconds
                        Thread.sleep(1000);
                        n++;
                        progressBar.setValue(n * 10);
                    }

                    progressBar.setValue(100);
                    labelProgress.setVisible(true);
                    buttonFDActivator.setEnabled(true);

                    writeDataInto(driveNa);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });

        // Start the thread
        timerThread.start();

    }//GEN-LAST:event_buttonFDActivatorActionPerformed

    private void writeDataInto(String driveLetter) {

        String tgl = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
        String sn = textfieldSerialNumberUSBDevice.getText();
        String appName = comboboxAppProfileName.getSelectedItem().toString();

        SingleData n = new SingleData(sn, appName, tgl);
        DataTransporter.writeNow(n.toString(), driveLetter);

    }

    ImageIcon iconUSBOff = new javax.swing.ImageIcon(getClass().getResource("/frames/images/usb-drive-off-32.png"));
    ImageIcon iconUSBOn = new javax.swing.ImageIcon(getClass().getResource("/frames/images/usb-drive-on-32.png"));

    boolean foundUSB = false;

    private void activateIcon() {

        if (foundUSB) {
            labelUSBIcon.setIcon(iconUSBOn);

        } else {
            labelUSBIcon.setIcon(iconUSBOff);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlashDiskMakerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlashDiskMakerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlashDiskMakerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlashDiskMakerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlashDiskMakerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDetectUSBDrives;
    private javax.swing.JButton buttonFDActivator;
    private javax.swing.JComboBox<String> comboboxAppProfileName;
    private javax.swing.JComboBox<String> comboboxUSBDriveActive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelProgress;
    private javax.swing.JLabel labelUSBIcon;
    private javax.swing.JPanel panelProgress;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField textfieldSerialNumberUSBDevice;
    // End of variables declaration//GEN-END:variables
}
