package frames;

import helper.DBTransactions;
import helper.PopupMessage;
import config.SystemPath;
import frames.forms.WebToAPKForm;
import helper.TableRender;
import helper.objects.WebToAPK;
import java.awt.Desktop;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URI;
import javax.swing.JLabel;

/**
 *
 * @author staff
 */
public class WebToAPKManagerFrame extends WindowsSkeleton {

    /**
     * Creates new form AppProfileManagerFrame
     */
    DBTransactions db = new DBTransactions(SystemPath.DB_FILE);
    TableRender tbrend = new TableRender();

    DashboardFrame parent;
    WebToAPKForm child;

    public WebToAPKManagerFrame() {
        prepareUI();
    }

    public WebToAPKManagerFrame(DashboardFrame formNa) {

        parent = formNa;
        prepareUI();
    }

    private void prepareUI() {
        super.windowsTheme();
        initComponents();
        refresh();
        this.toFront();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableWebToAPKManager = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        button_request_more = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        button_refresh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelAppDescription = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        tableWebToAPKManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "[#]", "id", "Queue ID", "App Name", "URL", "Status", "Submitted Date", "Completed Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableWebToAPKManager.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tableWebToAPKManagerMouseMoved(evt);
            }
        });
        tableWebToAPKManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tableWebToAPKManagerMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(tableWebToAPKManager);
        if (tableWebToAPKManager.getColumnModel().getColumnCount() > 0) {
            tableWebToAPKManager.getColumnModel().getColumn(0).setMinWidth(30);
            tableWebToAPKManager.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableWebToAPKManager.getColumnModel().getColumn(0).setMaxWidth(30);
            tableWebToAPKManager.getColumnModel().getColumn(1).setMinWidth(0);
            tableWebToAPKManager.getColumnModel().getColumn(1).setPreferredWidth(0);
            tableWebToAPKManager.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(544, 40));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        button_request_more.setText("Request More");
        button_request_more.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_request_moreActionPerformed(evt);
            }
        });
        jPanel2.add(button_request_more);

        button_cancel.setText("Cancel Request");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });
        jPanel2.add(button_cancel);

        button_refresh.setText("Refresh");
        button_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_refreshActionPerformed(evt);
            }
        });
        jPanel2.add(button_refresh);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        labelAppDescription.setText("-hover your app data above to see the result here-");
        jPanel3.add(labelAppDescription);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);
        jPanel4.setPreferredSize(new java.awt.Dimension(338, 100));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Web To APK Manager");
        jPanel4.add(jLabel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_request_moreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_request_moreActionPerformed

        if (child != null) {
            if (!child.isDisplayable()) {
                child = new WebToAPKForm(this);
                child.setVisible(true);
            }

            this.setEnabled(false);

        } else {
            child = new WebToAPKForm(this);
            child.setVisible(true);

            this.setEnabled(false);
        }

    }//GEN-LAST:event_button_request_moreActionPerformed

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed

        int nomer = tbrend.getCheckedData(tableWebToAPKManager, 1);
        if (nomer != TableRender.DATA_NOT_AVAILABLE) {
            WebToAPK data = db.select_specific_WebToAPK(nomer);
            data.setStatus("cancelled by user");
            db.update_WebToAPK(data);
            refresh();
        } else {
            PopupMessage.showError("no data selected!");
        }


    }//GEN-LAST:event_button_cancelActionPerformed

    MouseAdapter mdfor_download;

    private void tableWebToAPKManagerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableWebToAPKManagerMouseMoved

        Point point = evt.getPoint();
        int row = tableWebToAPKManager.rowAtPoint(point);

        System.out.println("Baris ke " + row);

        if (row != TableRender.DATA_NOT_AVAILABLE) {
            int id = (Integer) tableWebToAPKManager.getValueAt(row, 1);
            WebToAPK data = db.select_specific_WebToAPK(id);

            System.out.println("Datana " + data.getDownload_link());

            if (data.getDownload_link() != null) {
                labelAppDescription.setText("click the link here : " + data.getDownload_link());
                setAction(labelAppDescription, data.getDownload_link());
            } else {
                labelAppDescription.setText("-");
                if (mdfor_download != null) {
                    labelAppDescription.removeMouseListener(mdfor_download);
                }
            }

        }

    }//GEN-LAST:event_tableWebToAPKManagerMouseMoved

    private void setAction(JLabel jlab, String dl) {
        mdfor_download = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    // Perform the action when the label is clicked
                    Desktop.getDesktop().browse(new URI(dl));
                } catch (Exception ex) {

                }
            }
        };

        jlab.addMouseListener(mdfor_download);
    }

    private void tableWebToAPKManagerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableWebToAPKManagerMouseExited
        labelAppDescription.setText("-hover your app data above to see the result here-");
    }//GEN-LAST:event_tableWebToAPKManagerMouseExited

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        if (parent != null) {
            parent.setEnabled(true);
            parent.toFront();
        }
    }//GEN-LAST:event_formWindowClosed

    private void button_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_refreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_refreshActionPerformed

    public void refresh() {
        tbrend.render_WebToAPK(tableWebToAPKManager, db.select_all_WebToAPK());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WebToAPKManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WebToAPKManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WebToAPKManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WebToAPKManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WebToAPKManagerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_refresh;
    private javax.swing.JButton button_request_more;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAppDescription;
    private javax.swing.JTable tableWebToAPKManager;
    // End of variables declaration//GEN-END:variables
}
