/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames.forms;

import frames.DashboardFrame;
import helper.DBTransactions;
import config.SystemPath;
import frames.WindowsSkeleton;
import helper.UIForm;
import helper.objects.AppsProfile;
import helper.objects.DownloadLink;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author staff
 */
public class DownloadLinkForm extends WindowsSkeleton {

    /**
     * Creates new form NewAppsProfileFrame
     */
    boolean editMode = false;
    DownloadLink dataTemp = null;
    DashboardFrame parent = null;

    private void prepareUI() {
        super.windowsTheme();
        initComponents();

        this.toFront();

        labelLastDownload.setText("");
        labelTotalDownload.setText("");
        
        refresh();
    }

    public DownloadLinkForm() {
      
        prepareUI();

    }

    public DownloadLinkForm(DashboardFrame parentNa) {
        parent = parentNa;
        prepareUI();
    }

    public void refresh() {

        comboboxAppsProfile.removeAllItems();

        ArrayList<AppsProfile> data = db.select_all_AppProfile();
        for (AppsProfile ap : data) {
            comboboxAppsProfile.addItem(ap.getName() + " ver : " + ap.getVersion() + " platform type : " + ap.getPlatform_Type());
        }
    }

    public void setData(DownloadLink dataNa) {
        if (dataNa != null) {
            // mode edit
            editMode = true;
            dataTemp = dataNa;
        }

        UIForm.setComboboxData(dataNa.getApp_name(), comboboxAppsProfile);
        UIForm.setRadioButtonData(dataNa.getLink_mode(), radio_candy, radio_simple, radio_vip);
        textfield_directURL.setText(dataNa.getLast_download());

        labelLastDownload.setText(dataNa.getLast_download());
        labelTotalDownload.setText(dataNa.getTotal_overall() + " user download.");
    }

    DBTransactions db = new DBTransactions(SystemPath.DB_FILE);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        button_save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        radio_simple = new javax.swing.JRadioButton();
        radio_candy = new javax.swing.JRadioButton();
        radio_vip = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboboxAppsProfile = new javax.swing.JComboBox<>();
        labelLinkPreview = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelLastDownload = new javax.swing.JLabel();
        labelTotalDownload = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textfield_directURL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_generatedHTML = new javax.swing.JTextArea();
        labelCopied = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });
        getContentPane().add(button_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 87, 36));

        jLabel2.setText("App Name : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 98, -1, -1));

        buttonGroup1.add(radio_simple);
        radio_simple.setSelected(true);
        radio_simple.setText("Simple");
        radio_simple.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_simpleItemStateChanged(evt);
            }
        });
        getContentPane().add(radio_simple, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        buttonGroup1.add(radio_candy);
        radio_candy.setText("Candy");
        radio_candy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_candyItemStateChanged(evt);
            }
        });
        getContentPane().add(radio_candy, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        buttonGroup1.add(radio_vip);
        radio_vip.setText("VIP");
        radio_vip.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_vipItemStateChanged(evt);
            }
        });
        getContentPane().add(radio_vip, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabel3.setText("Link Mode :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setText("Direct URL App : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Download Link Renderer");
        jPanel1.add(jLabel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 50));

        comboboxAppsProfile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxAppsProfile.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxAppsProfileItemStateChanged(evt);
            }
        });
        getContentPane().add(comboboxAppsProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 95, 186, -1));

        labelLinkPreview.setText("-");
        getContentPane().add(labelLinkPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 180, 33));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Statistics"));

        jLabel1.setText("Last Download : ");

        jLabel6.setText("Total Overall :");

        labelLastDownload.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelLastDownload.setText("dd-mm-yyyy from IP.ADDRESS");

        labelTotalDownload.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTotalDownload.setText("0 user download.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalDownload)
                    .addComponent(labelLastDownload))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelLastDownload))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelTotalDownload))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 370, 110));

        jLabel7.setText("Preview : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        getContentPane().add(textfield_directURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 230, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/copy-icon-32.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        textarea_generatedHTML.setColumns(20);
        textarea_generatedHTML.setRows(5);
        jScrollPane1.setViewportView(textarea_generatedHTML);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 220, -1));

        labelCopied.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCopied.setText("Copied to Clipboard!");
        getContentPane().add(labelCopied, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 120, -1));

        jLabel10.setText("Generated Js Code :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed

        AppsProfile data = new AppsProfile();

        if (!editMode) {
            db.insert_AppProfile(data);
        } else {

            db.update_AppProfile(data);
        }

        dispose();

    }//GEN-LAST:event_button_saveActionPerformed

    private void comboboxAppsProfileItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxAppsProfileItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // request on POST to server
            renderPreview();
        }

    }//GEN-LAST:event_comboboxAppsProfileItemStateChanged

    ImageIcon candyIcon = new javax.swing.ImageIcon(getClass().getResource("/frames/images/candy-button.png"));
    ImageIcon vipIcon = new javax.swing.ImageIcon(getClass().getResource("/frames/images/vip-button.png"));
    ImageIcon simpleIcon = new javax.swing.ImageIcon(getClass().getResource("/frames/images/simple-button.png"));

    private void renderPreview() {

        if (radio_candy.isSelected()) {
            labelLinkPreview.setIcon(candyIcon);
        } else if (radio_simple.isSelected()) {
            labelLinkPreview.setIcon(simpleIcon);
        } else if (radio_vip.isSelected()) {
            labelLinkPreview.setIcon(vipIcon);
        }

    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        if (parent != null) {
            parent.setEnabled(true);
            parent.toFront();
        }

    }//GEN-LAST:event_formWindowClosed

    private void radio_simpleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_simpleItemStateChanged
        whenSelectedRenderProperly(evt);
    }//GEN-LAST:event_radio_simpleItemStateChanged

    private void radio_candyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_candyItemStateChanged
        whenSelectedRenderProperly(evt);
    }//GEN-LAST:event_radio_candyItemStateChanged

    private void radio_vipItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_vipItemStateChanged
        whenSelectedRenderProperly(evt);
    }//GEN-LAST:event_radio_vipItemStateChanged

    private void whenSelectedRenderProperly(ItemEvent evt) {
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // request on POST to server
            renderPreview();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DownloadLinkForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DownloadLinkForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DownloadLinkForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DownloadLinkForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DownloadLinkForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_save;
    private javax.swing.JComboBox<String> comboboxAppsProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCopied;
    private javax.swing.JLabel labelLastDownload;
    private javax.swing.JLabel labelLinkPreview;
    private javax.swing.JLabel labelTotalDownload;
    private javax.swing.JRadioButton radio_candy;
    private javax.swing.JRadioButton radio_simple;
    private javax.swing.JRadioButton radio_vip;
    private javax.swing.JTextArea textarea_generatedHTML;
    private javax.swing.JTextField textfield_directURL;
    // End of variables declaration//GEN-END:variables
}
