package frames.forms;

import frames.DashboardFrame;
import helper.DBTransactions;
import config.SystemPath;
import frames.WebToAPKManagerFrame;
import helper.DateHelper;
import helper.UIForm;
import helper.objects.AppsProfile;
import helper.objects.DownloadLink;
import helper.objects.WebToAPK;
import java.util.ArrayList;

/**
 *
 * @author staff
 */
public class WebToAPKForm extends javax.swing.JFrame {

    /**
     * Creates new form NewAppsProfileFrame
     */
    boolean editMode = false;
    DownloadLink dataTemp = null;
    WebToAPKManagerFrame parent = null;
    ArrayList<AppsProfile> localData;

    public WebToAPKForm() {
        prepareUI();
    }

    public WebToAPKForm(WebToAPKManagerFrame parentNa) {
        parent = parentNa;
        prepareUI();
    }

    private void prepareUI() {
        initComponents();

        label_queue_id.setVisible(false);
        
        refresh();
    }

    public void refresh() {

        comboboxAppsProfile.removeAllItems();

        localData = db.select_all_AppProfile();
        for (AppsProfile ap : localData) {
            if (ap.getPlatform_Type().toLowerCase().contains("web")) {
                comboboxAppsProfile.addItem(ap.getName() + " ver : " + ap.getVersion() + " platform type : " + ap.getPlatform_Type());
            }
        }
    }

    public void setData(DownloadLink dataNa) {
        if (dataNa != null) {
            // mode edit
            editMode = true;
            dataTemp = dataNa;
        }

        UIForm.setComboboxData(dataNa.getApp_name(), comboboxAppsProfile);

    }

    DBTransactions db = new DBTransactions(SystemPath.DB_FILE);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        label_queue_id = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboboxAppsProfile = new javax.swing.JComboBox<>();
        textfield_directURL = new javax.swing.JTextField();
        button_build = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("App Name : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 98, -1, -1));

        label_queue_id.setText("ID Queue #");
        getContentPane().add(label_queue_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Web to APK");
        jPanel1.add(jLabel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 60));

        comboboxAppsProfile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxAppsProfile.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxAppsProfileItemStateChanged(evt);
            }
        });
        getContentPane().add(comboboxAppsProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 95, 290, -1));
        getContentPane().add(textfield_directURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 230, -1));

        button_build.setText("Build On Cloud!");
        button_build.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_buildActionPerformed(evt);
            }
        });
        getContentPane().add(button_build, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 120, 36));

        jLabel6.setText("Web URL :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxAppsProfileItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxAppsProfileItemStateChanged

        // track the id selected
        postItem = comboboxAppsProfile.getSelectedIndex();

        System.out.println("You choose " + postItem);

    }//GEN-LAST:event_comboboxAppsProfileItemStateChanged

    int postItem = 0;

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        if (parent != null) {
            parent.setEnabled(true);
            parent.toFront();
        }

    }//GEN-LAST:event_formWindowClosed

    private void button_buildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_buildActionPerformed

        WebToAPK data = new WebToAPK();
        data.setAppname(localData.get(postItem).getName());
        data.setStatus("in progress...");
        data.setUrl(textfield_directURL.getText());
        data.setSubmitted_date(DateHelper.getDateNow(DateHelper.FORMAT_COMPUTER));

        db.insert_WebToAPK(data);
    }//GEN-LAST:event_button_buildActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WebToAPKForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WebToAPKForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WebToAPKForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WebToAPKForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WebToAPKForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_build;
    private javax.swing.JComboBox<String> comboboxAppsProfile;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_queue_id;
    private javax.swing.JTextField textfield_directURL;
    // End of variables declaration//GEN-END:variables
}
